<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>Sm0kiSoloCoach</AssemblyName>
    <RootNamespace>Sm0kiSoloCoach</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="DemoFile.Game.Cs" Version="0.40.1" />
  </ItemGroup>
</Project>
